
FROM        --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL       author="Batuhan Aydemir" maintainer="batuhan.aydemir@rustopic.com"

LABEL       org.opencontainers.image.source="https://github.com/rustopic/runtimes"
LABEL       org.opencontainers.image.licenses=MIT

RUN         apk add --update --no-cache ca-certificates curl git jq wget
